pr:
  - master

variables:
  - name: functions-path
    value: 'src/functions'
  - name: terraform-path
    value: 'src/infrastructure'

  - group: terraform-auth-variables

stages:
  - stage: python
    displayName: Python
    dependsOn: []
    jobs:
      - job: python_validation
        displayName: Python validation
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.6'
              addToPath: true
              architecture: 'x64'
            displayName: 'Use python 3.6'
          - script: |
              python -m pip install --upgrade pip
              pip install -r $(functions-path)/requirements.txt
              pip install mypy
              pip install flake8
            displayName: 'Install python validation tools'
          - script: |
              flake8 $(functions-path) --count --select=E9,F63,F7,F82 --show-source --statistics
              flake8 $(functions-path) --count --exit-zero --max-complexity=10 --statistics
            displayName: 'Validate flake8'
          - script: mypy $(functions-path)
            displayName: 'Validate my-py'

  - stage: Terraform
    displayName: Terraform
    dependsOn: []
    jobs:
      - job: terraform_validation
        displayName: Terraform validation
        steps:
          - script: terraform init $(terraform-path)
            displayName: 'Terraform Init'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

          - script: terraform fmt -check $(terraform-path)
            displayName: 'Terraform Format'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

          - script: terraform validate -no-color $(terraform-path)
            displayName: 'Terraform Validate'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

          - script: terraform plan -no-color $(terraform-path)
            displayName: 'Terraform Plan'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)



